name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 13.232.220.165
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            REPO_NAME="flask-sample"
            cd $REPO_NAME || git clone https://github.com/jegansekar112/${GITHUB_REPOSITORY}.git $REPO_NAME
            cd $REPO_NAME
            git pull origin main
            docker build -t $REPO_NAME .
            docker stop $REPO_NAME || true
            docker rm $REPO_NAME || true
            docker run -d --name $REPO_NAME -p 80:80 $REPO_NAME
