# .github/workflows/deploy-main.yml
name: Deploy Main Branch

on:
  push:
    branches:
      - main

jobs:
  call-deploy:
    uses: workflow/.github/workflows/deploy-ec2.yml
    with:
      repo_name: "flask-sample"
      host: "13.232.220.165"
      port: "5000"
    secrets:
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
